version: '3'

services:
  web:
    build:
      context: .
      dockerfile: app/Dockerfile.web
    env_file: .env
    environment:
      DEBUG: "True"
      DATABASE_URL: "postgres://postgres:hackme@db:5432/postgres"
      MONGODB_URI: "mongodb://mongo:27017/main"
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
      - ./lib:/pythonpkg/lib
      - ./feeds:/pythonpkg/feeds
    depends_on:
      - db
      - mongo
  web-migrate:
    build:
      context: .
      dockerfile: app/Dockerfile.web
    command: "'sleep 1; python manage.py migrate'"
    env_file: .env
    environment:
      DATABASE_URL: "postgres://postgres:hackme@db:5432/postgres"
    volumes:
      - ./app:/app
    depends_on:
      - db
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: hackme
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  localtunnel:
    image: efrecon/localtunnel
    env_file: .env
    restart: always
    depends_on:
      - web
    command: --local-host web --port 8080 --subdomain ${TUNNEL_NAME}

volumes:
  db_data: {}
  mongo_data: {}
