apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: entry-deployment
  labels:
    app: entry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: entry
  template:
    metadata:
      labels:
        app: entry
    spec:
      containers:
      - name: nginx-autossl
        image: wdr-data/nginx-autossl
        ports:
        - containerPort: 80
        - containerPort: 443

---

apiVersion: v1
kind: Service
metadata:
  name: entry-service
spec:
  type: NodePort
  selector:
    app: entry
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 8000
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
    nodePort: 8443
