---

- hosts: localhost
  tasks:
    - include_tasks: utils/k8s-creds.yml
    - name: Create Kubernetes Namespaces
      kubernetes:
        api_endpoint: "api.{{ k8s_url }}"
        username: admin
        password: "{{ k8s_credentials }}"
        inline_data: |
          apiVersion: v1
          kind: Namespace
          metadata:
            name: {{ namespace }}-{{ item }}
      items: "{{ stages }}"
    - name: Install Kubernetes Addons
      command: "kubectl apply -f {{ item }}"
      items:
        - "https://raw.githubusercontent.com/mittwald/kubernetes-secret-generator/master/deploy/secret-generator-rbac.yaml"
        - "https://raw.githubusercontent.com/mittwald/kubernetes-secret-generator/master/deploy/secret-generator.yaml"
      register: k8s_addon_apply
      changed_when: "(k8s_addon_apply.stdout_lines | map('regex_search', '^.*unchanged$') | select('string') | list | length) < (k8s_addon_apply.stdout_lines | length)"
