---

- hosts: localhost
  tasks:
    - include_tasks: utils/k8s-creds.yml
    - name: Store Kubernetes Secrets
      include_tasks: utils/k8s-secret.yml
      vars:
        stage: "{{ item[1] }}"
        secret:
          name: "{{ item[0]['name'] }}"
          entries: "{{ item[0]['values'][item[1]] }}"
      with_nested:
        - "{{ insert_secrets }}"
        - "{{ stages }}"
