# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=64, unique=True, verbose_name='User ID')),
                ('state', models.CharField(blank=True, max_length=64, null=True, verbose_name='State')),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hinzugefügt am')),
            ],
            options={
                'verbose_name': 'Facebook User',
                'verbose_name_plural': 'Facebook User',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Hinweis: Wird nicht ausgespielt', max_length=128, unique=True, verbose_name='Titel')),
                ('content', models.CharField(blank=True, help_text='Text der Info', max_length=600, null=True, verbose_name='Inhalt')),
                ('media', models.FileField(blank=True, null=True, upload_to='', verbose_name='Medien-Anhang')),
                ('attachment_id', models.CharField(blank=True, help_text='Wird automatisch ausgefüllt', max_length=64, null=True, verbose_name='Facebook Attachment ID')),
            ],
            options={
                'verbose_name': 'Info',
                'verbose_name_plural': 'Infos',
            },
        ),
        migrations.CreateModel(
            name='Push',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200, verbose_name='Überschrift')),
                ('text', models.CharField(max_length=200, verbose_name='Intro-Text')),
                ('media', models.FileField(blank=True, null=True, upload_to='', verbose_name='Medien-Anhang Intro')),
                ('media_note', models.CharField(blank=True, help_text='z. B. Bildrechte', max_length=128, null=True, verbose_name='Anmerkung')),
                ('attachment_id', models.CharField(blank=True, help_text='Wird automatisch ausgefüllt', max_length=64, null=True, verbose_name='Facebook Attachment ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Für morgens auf 6:00, für abends auf 18:00 timen (Uhr-Symbol)', verbose_name='Veröffentlicht am')),
                ('published', models.BooleanField(default=False, verbose_name='Veröffentlicht?')),
                ('breaking', models.BooleanField(default=False, help_text='Breaking-News werden außerhalb der regelmäßigen Push-Zyklen zu der angegebenen Zeit gesendet', verbose_name='Breaking?')),
                ('delivered', models.BooleanField(default=False, help_text='Wurde der Push bereits vom Bot versendet? Nur relevant für Breaking-News.', verbose_name='Versendet?')),
            ],
            options={
                'verbose_name': 'Meldung',
                'verbose_name_plural': 'Meldungen',
            },
        ),
        migrations.CreateModel(
            name='PushFragment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=20, verbose_name='Frage')),
                ('text', models.CharField(max_length=600, verbose_name='Text')),
                ('media', models.FileField(blank=True, null=True, upload_to='', verbose_name='Medien-Anhang')),
                ('media_note', models.CharField(blank=True, help_text='z. B. Bildrechte', max_length=128, null=True, verbose_name='Anmerkung')),
                ('attachment_id', models.CharField(blank=True, help_text='Wird automatisch ausgefüllt', max_length=64, null=True, verbose_name='Facebook Attachment ID')),
                ('push', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragments', related_query_name='fragment', to='backend.Push')),
            ],
            options={
                'verbose_name': 'Meldungs-Fragment',
                'verbose_name_plural': 'Meldungs-Fragmente',
            },
        ),
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(help_text='Der Eingabetext des Nutzers', max_length=128, unique=True, verbose_name='Eingabe')),
                ('output', models.CharField(blank=True, help_text='Die Antwort, die der Bot auf die Eingabe geben soll', max_length=640, null=True, verbose_name='Antwort')),
                ('media', models.FileField(blank=True, null=True, upload_to='', verbose_name='Medien-Anhang')),
                ('attachment_id', models.CharField(blank=True, help_text='Wird automatisch ausgefüllt', max_length=64, null=True, verbose_name='Facebook Attachment ID')),
            ],
            options={
                'verbose_name': 'Wiki-Eintrag',
                'verbose_name_plural': 'Wiki-Einträge',
            },
        ),
    ]
