# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 15:20
from __future__ import unicode_literals

import backend.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20171108_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Push',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200, verbose_name='Titel')),
                ('text', models.CharField(max_length=200, verbose_name='Intro-Text')),
                ('pub_date', models.DateTimeField(default=backend.models.default_pub_date, verbose_name='Versenden am')),
            ],
            options={
                'verbose_name_plural': 'Push',
                'verbose_name': 'Push',
            },
        ),
        migrations.AddField(
            model_name='report',
            name='push',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', related_query_name='report', to='backend.Push'),
        ),
    ]
