# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20171108_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='push',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Freigegeben'),
        ),
    ]
