# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20171108_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='push',
            name='delivered',
            field=models.BooleanField(default=False, editable=False, help_text='Wurde dieser Push bereits versendet?', verbose_name='Versendet'),
        ),
    ]
