# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_push_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='push',
            name='delivered',
            field=models.BooleanField(default=False, help_text='Wurde dieser Push bereits versendet?', verbose_name='Versendet'),
        ),
    ]
