# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20171108_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('slug', models.CharField(blank=True, max_length=200, null=True, verbose_name='Slug')),
                ('text', models.CharField(max_length=640, verbose_name='Text')),
                ('media', models.FileField(blank=True, null=True, upload_to='', verbose_name='Medien-Anhang Intro')),
                ('media_note', models.CharField(blank=True, help_text='z. B. Bildrechte', max_length=128, null=True, verbose_name='Anmerkung')),
                ('attachment_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Facebook Attachment ID')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
            },
        ),
        migrations.CreateModel(
            name='StoryFragment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button', models.CharField(max_length=20, verbose_name='Button-Text')),
                ('text', models.CharField(max_length=640, verbose_name='Text')),
                ('media', models.FileField(blank=True, null=True, upload_to='', verbose_name='Medien-Anhang')),
                ('media_note', models.CharField(blank=True, max_length=128, null=True, verbose_name='Anmerkung')),
                ('attachment_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Facebook Attachment ID')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragments', related_query_name='fragment', to='backend.Story')),
            ],
            options={
                'verbose_name': 'Story-Fragment',
                'verbose_name_plural': 'Story-Fragmente',
            },
        ),
        migrations.AlterField(
            model_name='info',
            name='attachment_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Facebook Attachment ID'),
        ),
        migrations.AlterField(
            model_name='push',
            name='delivered',
            field=models.BooleanField(default=False, verbose_name='Versendet'),
        ),
        migrations.AlterField(
            model_name='push',
            name='text',
            field=models.CharField(max_length=640, verbose_name='Intro-Text'),
        ),
        migrations.AlterField(
            model_name='report',
            name='text',
            field=models.CharField(max_length=640, verbose_name='Intro-Text'),
        ),
        migrations.AlterField(
            model_name='reportfragment',
            name='attachment_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Facebook Attachment ID'),
        ),
        migrations.AlterField(
            model_name='reportfragment',
            name='text',
            field=models.CharField(max_length=640, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='attachment_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Facebook Attachment ID'),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='output',
            field=models.CharField(blank=True, max_length=640, null=True, verbose_name='Antwort'),
        ),
    ]
