# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20171109_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='discipline',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Disziplin'),
        ),
        migrations.AddField(
            model_name='report',
            name='sport',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sportart'),
        ),
    ]
