# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20171109_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyfragment',
            name='link_story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to='backend.Story'),
        ),
    ]
