# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20171109_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='media_note',
        ),
        migrations.RemoveField(
            model_name='reportfragment',
            name='media_note',
        ),
        migrations.RemoveField(
            model_name='story',
            name='media_note',
        ),
        migrations.RemoveField(
            model_name='storyfragment',
            name='media_note',
        ),
    ]
