# Generated by Django 2.0.1 on 2018-01-22 12:54

from django.db import migrations, models


def save_reports(apps, schema_editor):
    Report = apps.get_model('backend', 'Report')

    for report in Report.objects.all():
        report.push.reports.add(report)


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20171109_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='push',
            name='reports',
            field=models.ManyToManyField(related_name='pushes', to='backend.Report'),
        ),
        migrations.RunPython(save_reports),
        migrations.RemoveField(
            model_name='report',
            name='push',
        ),
    ]
