# Generated by Django 2.0.1 on 2018-01-22 13:26

from django.db import migrations
import sortedm2m.fields
from sortedm2m.operations import AlterSortedManyToManyField


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20180122_1354'),
    ]

    operations = [
        AlterSortedManyToManyField(
            model_name='push',
            name='reports',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='pushes', to='backend.Report'),
        ),
    ]
