# Generated by Django 2.0.1 on 2018-01-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20180124_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='push',
            name='outro',
            field=models.CharField(blank=True, max_length=640, verbose_name='Outro-Text'),
        ),
    ]
