# Generated by Django 2.0.2 on 2018-02-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20180210_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='push',
            name='attachment_id_intro',
            field=models.CharField(blank=True, help_text='Wird automatisch ausgefüllt', max_length=64, null=True, verbose_name='Facebook Attachment ID Intro'),
        ),
        migrations.AddField(
            model_name='push',
            name='attachment_id_outro',
            field=models.CharField(blank=True, help_text='Wird automatisch ausgefüllt', max_length=64, null=True, verbose_name='Facebook Attachment ID Outro'),
        ),
        migrations.AddField(
            model_name='push',
            name='media_intro',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Medien-Anhang Intro'),
        ),
        migrations.AddField(
            model_name='push',
            name='media_outro',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Medien-Anhang Outro'),
        ),
    ]
