FROM python:3.6-alpine

RUN apk --no-cache add musl-dev linux-headers g++ tini postgresql-dev && \
    pip install numpy # installing beforehand so it can get cached by docker

COPY Pipfile* /app/

WORKDIR /app

RUN pip install pipenv && \
    pipenv lock --requirements > /tmp/requirements-lock.txt && \
    pip install -r /tmp/requirements-lock.txt && \
    pipenv --rm

COPY app /app
COPY lib /pythonpkg/lib
COPY feeds /pythonpkg/feeds

ENV PYTHONPATH=${PYTHONPATH}:/pythonpkg

RUN SECRET_KEY=1 python manage.py collectstatic --noinput --clear

RUN adduser -D webuser
USER webuser

EXPOSE 8080
ENV PORT=8080
ENV LOG_LEVEL=info
ENV GUNICORN_ARGS ""

ENTRYPOINT ["sh", "-c"]
CMD ["gunicorn -b :$PORT -k 'eventlet' main.wsgi --capture-output --log-file - --log-level $LOG_LEVEL $GUNICORN_ARGS"]
