FROM python:3.6-alpine

RUN apk --no-cache add musl-dev linux-headers g++ gcc tini postgresql-dev libxslt-dev libxml2-dev \
    && pip install numpy lxml pipenv # installing beforehand so it can get cached by docker

COPY Pipfile* /app/

WORKDIR /app

RUN pipenv install --system

COPY app /app
COPY lib /pythonpkg/lib
COPY feeds /pythonpkg/feeds
COPY worker/mrq-config.py /mrq-config.py

ENV PYTHONPATH=${PYTHONPATH}:/pythonpkg

RUN SECRET_KEY=1 python manage.py collectstatic --noinput --clear

EXPOSE 8080
ENV PORT=8080
ENV LOG_LEVEL=info
ENV GUNICORN_ARGS ""

ENTRYPOINT ["sh", "-c"]
CMD ["gunicorn -b :$PORT -k 'eventlet' main.wsgi --capture-output --log-file - --log-level $LOG_LEVEL $GUNICORN_ARGS"]
