FROM python:3.6

RUN apt-get update && apt-get install -yq \
    g++ gcc postgresql-server-dev-all libxslt-dev libxml2-dev locales \
    && pip install numpy lxml pipenv # installing beforehand so it can get cached by docker

RUN echo 'en_US.UTF-8 UTF-8\nde_DE.UTF-8 UTF-8' >> /etc/locale.gen && \
    locale-gen && \
    update-locale LANG=de_DE.UTF-8

ENV LANG=de_DE.UTF-8
ENV LC_ALL=de_DE.UTF-8

COPY Pipfile* /app/

WORKDIR /app

RUN pipenv install --system

COPY app /app
COPY lib /pythonpkg/lib
COPY feeds /pythonpkg/feeds
COPY worker/mrq-config.py /mrq-config.py

ENV PYTHONPATH=${PYTHONPATH}:/pythonpkg

RUN SECRET_KEY=1 python manage.py collectstatic --noinput --clear

EXPOSE 8080
ENV PORT=8080
ENV LOG_LEVEL=info
ENV GUNICORN_ARGS ""

ENTRYPOINT ["sh", "-c"]
CMD ["gunicorn -b :$PORT -k 'gevent' main.wsgi --capture-output --log-file - --log-level $LOG_LEVEL $GUNICORN_ARGS"]
