FROM nomaster/nginx

ADD nginx.conf /usr/local/openresty/nginx/conf/nginx.conf
ADD autossl-http.conf /usr/local/openresty/nginx/conf/autossl-http.conf
ADD autossl-servers.conf /usr/local/openresty/nginx/conf/autossl-servers.conf
