
Parallel Slalom: Parallel
Parallel-Riesenslalom: Parallel
Staffel 4x7,5km: Staffel
Staffel 4x6km: Staffel
Staffel single mixed: Staffel
Staffel mixed 2x6km + 2x7,5km: Staffel
20km Einzel: Einzel
15km Einzel: Einzel
10km Verfolgung: Verfolgung
12,5km Verfolgung: Verfolgung
7,5km Sprint: Sprint
10km Sprint: Sprint
15km Massenstart: Massenstart
12,5km Massenstart: Massenstart
Alpine Kombination: Kombination