
Parallel Slalom: Parallel
Parallel-Riesenslalom: Parallel
Staffel 4x7,5km: Staffel
Staffel 4x6km: Staffel
Staffel single mixed: Staffel
Staffel mixed 2x6km + 2x7,5km: Staffel
20km Einzel: Einzel
15km Einzel: Einzel
10km Verfolgung: Verfolgung
12,5km Verfolgung: Verfolgung
7,5km Sprint: Sprint
10km Sprint: Sprint
15km Massenstart: Massenstart
12,5km Massenstart: Massenstart
Alpine Kombination: Kombination
HS 134 Einzel: Großschanze
HS 100 Einzel: Normalschanze
HS 110 Einzel: Großschanze
HS 95 Einzel: Normalschanze
HS 80 Einzel: Kleinschanze
HS 90 Einzel: Normalschanze
HS 105 Einzel: Normalschanze
HS 106 Einzel: Normalschanze
HS 108 Einzel: Normalschanze
HS 138 Einzel: Großschanze
HS 142 Einzel: Großschanze
HS 94 Einzel: Normalschanze
HS 115 Einzel: Großschanze
HS 120 Einzel: Großschanze
HS 125 Einzel: Großschanze
HS 130 Einzel: Großschanze
HS 135 Einzel: Großschanze
HS 140 Einzel: Großschanze
HS 145 Einzel: Großschanze
HS 150 Einzel: Großschanze
HS 155 Einzel: Großschanze
HS 160 Einzel: Großschanze
HS 165 Einzel: Großschanze
HS 170 Einzel: Großschanze
HS 175 Einzel: Großschanze
HS 180 Einzel: Großschanze
HS 185 Einzel: Flugschanze
HS 190 Einzel: Flugschanze
HS 195 Einzel: Flugschanze
HS 200 Einzel: Flugschanze
HS 210 Einzel: Flugschanze
HS 205 Einzel: Flugschanze
HS 215 Einzel: Flugschanze
HS 220 Einzel: Flugschanze
HS 225 Einzel: Flugschanze
HS 94 Team: Team Normalschanze
HS 95 Team: Team Normalschanze
HS 80 Team: Team Kleinschanze
HS 90 Team: Team Normalschanze
HS 105 Team: Team Normalschanze
HS 106 Team: Team Normalschanze
HS 108 Team: Team Normalschanze
HS 100 Team: Team Normalschanze
HS 115 Team: Teamspringen
HS 120 Team: Teamspringen
HS 125 Team: Teamspringen
HS 130 Team: Teamspringen
HS 134 Team: Teamspringen
HS 135 Team: Teamspringen
HS 138 Team: Teamspringen
HS 140 Team: Teamspringen
HS 142 Team: Teamspringen
HS 145 Team: Teamspringen
HS 150 Team: Teamspringen
HS 155 Team: Teamspringen
HS 160 Team: Teamspringen
HS 165 Team: Teamspringen
HS 170 Team: Teamspringen
HS 175 Team: Teamspringen
HS 180 Team: Teamspringen
HS 185 Team: Team Flugschanze
HS 190 Team: Team Flugschanze
HS 195 Team: Team Flugschanze
HS 200 Team: Team Flugschanze
HS 210 Team: Team Flugschanze
HS 205 Team: Team Flugschanze
HS 215 Team: Team Flugschanze
HS 220 Team: Team Flugschanze
HS 225 Team: Team Flugschanze
10km Freistil: Freistil
15km: Skating
15km Skiathlon: Skiathlon
30km Skiathlon: Skiathlon
Bischofshofen: Vierschanzentournee
Garmisch-Partenkirchen: Vierschanzentournee
Innsbruck: Vierschanzentournee
Kombination:
Lillehammer Einzel: Raw-Air-Tour
Lillehammer Einzel Qualifikation: Raw-Air-Tour
Oslo Einzel: Raw-Air-Tour
Oslo Team: Raw-Air-Tour
Riesenslalom (Ersatz Maribor): Riesenslalom
Slalom (Ersatz Maribor): Slalom
Snowboardcross: Cross
Staffel 3000 m: Staffel
Staffel 5000 m: Staffel
Super G (Ersatz St. Moritz): Super G
Super-Kombination: Kombination
Trondheim Einzel: Raw-Air-Tour
Trondheim Einzel Qualifikation: Raw-Air-Tour
Vikersund Einzel: Raw-Air-Tour
Vikersund Einzel Qualifikation: Raw-Air-Tour
Vikersund Team: Raw-Air-Tour
15km Freistil: Skating
30km Skiathlon: Skiathlon
10km Freistil: Skating
Staffel 5000 m: Staffel
Staffel 3000 m: Staffel
Super-Kombination: Kombination
Super G: Super-G
Geamtwertung: Gesamtwertung
HS 134, 10km: Großschanze
HS 140, 10km: Großschanze
HS 106, 10km: Normalschanze
HS 106, 15km: Normalschanze
HS 100, Teamsprint 2x7,5km: Team
HS 100, 10km: Normalschanze
HS 130, Teamsprint 2x7,5km: Team
HS 142, 5km: Großschanze
HS 142, 10km: Großschanze
HS 130, 10km: Großschanze
HS 118, Team 4x5km: Team
HS 118, 10km: Großschanze
HS 134, Teamsprint 2x7,5km: Team
HS 100, Team 4x5km: Team
HS 138, 10km: Großschanze
HS 140, 10km: Großschanze
HS 96, 10km: Normalschanze
HS 109, 5km: Normalschanze
HS 109, 10km: Normalschanze
HS 109, 15km: Normalschanze
Parallel SL: Parallel
Parallel Riesenslalom: Parallel
Falun (SWE) Sprint Freistil: Freistil
Falun (SWE) 15km Massenstart klassisch: Massenstart
Falun (SWE) 15km Verfolgung Freistil: Verfolgung
Lenzerheide (SUI) Sprint Freistil: Sprint
Lenzerheide (SUI) 15km Freistil: Freistil
Lenzerheide (SUI) 15km Verfolgung Freistil: Verfolgung
Oberstdorf (GER) Sprint klassisch: Sprint
Oberstdorf (GER) 15km Freistil: Freistil
Val di Fiemme (ITA) 15km Massenstart klassisch: Massenstart
Val di Fiemme (ITA) 9km Verfolgung Freistil: Verfolgung
Lenzerheide (SUI) Sprint Freistil: Freistil
Lenzerheide (SUI) 10km klassisch: 10km
Lenzerheide (SUI) 10km Verfolgung Freistil: 10km Verfolgung
Oberstdorf (GER) Sprint klassisch: Sprint klassisch
Oberstdorf (GER) 10km Massenstart Freistil: Massenstart
Val di Fiemme (ITA) 10km Massenstart klassisch: Massenstart
Val di Fiemme (ITA) 9km Verfolgung Freistil: Verfolgung
Falun (SWE) 10km Verfolgung Freistil: Verfolgung
Falun (SWE) 10km Massenstart klassisch: Massenstart
Falun (SWE) 10km Verfolgung Freistil: Verfolgung
Teamsprint Freistil: Freistil
Sprint Freistil: Freistil
Teamsprint Freistil: Team
Sprint Freistil: Sprint
Sprint klassisch: Sprint
15km klassisch: 15km
15km Verfolgung klassisch: Verfolgung
Sprint Freistil: Freistil
15km klassisch: 15km
Sprint klassisch: Sprint
10km klassisch: 10km
10km Verfolgung klassisch: Verfolgung
Sprint Freistil: Sprint
15km Freistil: Freitstil
15km Verfolgung klassisch: Verfolgung
10km Freistil: Freitstil
10km Verfolgung klassisch: Verfolgung
Sprint klassisch: Sprint
2 x 15km Skiathlon: Skiathlon
