---
# result_type: TIME | POINTS
# competition_type: SINGLE | RACE | TOURNAMENT

- name: Biathlon
  topic_id: 1814
  result_type: TIME
  result_digits: 1
  competition_term: Rennen
  article: das
  disciplines:
    - name: Einzel
      competition_type: SINGLE
      article: das
    - name: Staffel
      competition_type: RACE
      article: die
    - name: Massenstart
      competition_type: RACE
      article: der
    - name: Verfolgung
      competition_type: RACE
      article: die
    - name: Sprint
      competition_type: SINGLE
      article: der

- name: Ski Alpin
  topic_id: 1773
  result_type: TIME
  result_digits: 2
  competition_term: Rennen
  article: das
  disciplines:
    - name: Abfahrt
      competition_type: SINGLE
      article: die
    - name: Super G
      competition_type: SINGLE
      article: der
    - name: Riesenslalom
      competition_type: SINGLE
      article: der
    - name: Slalom
      competition_type: SINGLE
      article: der
    - name: Kombination
      competition_type: SINGLE
      article: die
    - name: Parallel
      competition_type: TOURNAMENT
      article:

- name: Skispringen
  topic_id: 1789
  result_type: POINTS
  result_digits: 1
  competition_term: Springen
  article: das
  disciplines:
    - name: Großschanze
      competition_type: SINGLE
      article: das
    - name: Normalschanze
      competition_type: SINGLE
      article: das
    - name: Flugschanze
      competition_type: SINGLE
      article: das
    - name: Team Normalschanze
      competition_type: SINGLE
      article: das
    - name: Team Großschanze
      competition_type: SINGLE
      article: das
    - name: Team Normalschanze
      competition_type: SINGLE
      article: das

- name: Skeleton
  topic_id: None
  result_type: TIME
  result_digits: 2
  competition_term: Rennen
  article: das
  disciplines:
    - name: Skeleton
      competition_type: SINGLE
      article: das

- name: Ski Freestyle
  topic_id: None
  result_type: POINTS
  result_digits: 1
  competition_term: Event
  article: das
  disciplines:
    - name: Aerials
      competition_type: SINGLE
      article: das
    - name: Buckelpiste
      competition_type: SINGLE
      article: die
    - name: Slopestyle
      competition_type: SINGLE


- name: Eishockey
  topic_id: None
  result_type: POINTS
  result_digits: 1
  competition_term: Event
  article: das
  disciplines:
    - name: Olympia
      competition_type: TOURNAMENT
      article: das

- name: Bob
  topic_id: None
  result_type: POINTS
  result_digits: 1
  competition_term: Event
  article: das
  disciplines:
    - name: Zweierbob
      competition_type: SINGLE
      article: das
    - name: Viererbob
      competition_type: SINGLE
      article: das

- name: Curling
  topic_id: None
  result_type: POINTS
  result_digits: 1
  competition_term: Event
  article: das
  disciplines:
    - name: Olympia
      competition_type: TOURNAMENT
      article: das

- name: Eishockey
  topic_id: None
  result_type: POINTS
  result_digits: 1
  competition_term: Event
  article: das
  disciplines:
    - name: Olympia
      competition_type: TOURNAMENT
      article: das

- name: Eiskunstlauf
  topic_id: None
  result_type: POINTS
  result_digits: 1
  competition_term: Event
  article: das
  disciplines:
    - name: Aerials
      competition_type: SINGLE
      article: das

- name: Eisschnelllauf
  topic_id: None
  result_type: POINTS
  result_digits: 1
  competition_term: Event
  article: das
  disciplines:
    - name: Aerials
      competition_type: SINGLE
      article: das

- name: Nordische Kombination
  topic_id: None
  result_type: POINTS
  result_digits: 1
  competition_term: Event
  article: das
  disciplines:
    - name: Aerials
      competition_type: SINGLE
      article: das


- name: Rodeln
  topic_id: None
  result_type: POINTS
  result_digits: 1
  competition_term: Event
  article: das
  disciplines:
    - name: Einsitzer
      competition_type: SINGLE
      article: der
    - name: Doppelsitzer
      competition_type: SINGLE
      article: der
    - name: Teamwettbewerb
      competition_type: SINGLE
      article: der

- name: Shorttrack
  topic_id: None
  result_type: POINTS
  result_digits: 1
  competition_term: Event
  article: das
  disciplines:
    - name: Aerials
      competition_type: SINGLE
      article: das

- name: Skeleton
  topic_id: None
  result_type: POINTS
  result_digits: 1
  competition_term: Event
  article: das
  disciplines:
    - name: Skeleton
      competition_type: SINGLE
      article: das

- name: Ski Freestyle
  topic_id: None
  result_type: POINTS
  result_digits: 1
  competition_term: Event
  article: das
  disciplines:
    - name: Aerials
      competition_type: SINGLE
      article: das

- name: Ski Langlauf
  topic_id: None
  result_type: Time
  result_digits: 1
  competition_term: Event
  article: das
  disciplines:
    - name: Aerials
      competition_type: SINGLE
      article: das

- name: Skispringen
  topic_id: None
  result_type: POINTS
  result_digits: 1
  competition_term: Event
  article: das
  disciplines:
    - name: Aerials
      competition_type: SINGLE
      article: das

- name: Snowboard
  topic_id: None
  result_type: POINTS
  result_digits: 1
  competition_term: Event
  article: das
  disciplines:
    - name: Aerials
      competition_type: SINGLE
      article: das
...