---
# result_type: TIME | POINTS
# competition_type: SINGLE

- name: Biathlon
  topic_id: 1814
  result_type: TIME
  result_digits: 1
  competition_term: Rennen
  article: das
  pictogram: url
  disciplines:
    - name: Einzel
      competition_type: RACE
      result_at: '0'
      article: das
    - name: Staffel
      competition_type: RACE
      result_at: '0'
      article: die
    - name: Massenstart
      competition_type: RACE
      result_at: '0'
      article: der
    - name: Verfolgung
      competition_type: RACE
      result_at: '0'
      article: die
    - name: Sprint
      competition_type: SINGLE
      result_at: '0'
      article: der

- name: Ski Alpin
  topic_id: 1773
  result_type: TIME
  result_digits: 2
  competition_term: Rennen
  article: das
  disciplines:
    - name: Abfahrt
      competition_type: SINGLE
      result_at: '0'
      article: die
    - name: Super-G
      competition_type: SINGLE
      result_at: '0'
      article: der
    - name: Super G
      competition_type: SINGLE
      result_at: '0'
      article: der
    - name: Riesenslalom
      competition_type: SINGLE
      result_at: '0'
      article: der
    - name: Slalom
      competition_type: SINGLE
      result_at: '0'
      article: der
    - name: Kombination
      competition_type: SINGLE
      result_at: '0'
      article: die
    - name: Parallel
      competition_type: SINGLE
      result_at: '0'
      article:

- name: Skispringen
  topic_id: 1789
  result_type: POINTS
  result_digits: 1
  competition_term: Springen
  article: das
  disciplines:
    - name: Großschanze
      rounds: True
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: Normalschanze
      rounds: True
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: Flugschanze
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: Team Normalschanze
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: Teamspringen
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: Team Normalschanze
      competition_type: SINGLE
      result_at: '0'
      article: das

- name: Skeleton
  topic_id: null
  result_type: TIME
  result_digits: 2
  competition_term: Rennen
  article: das
  disciplines:
    - name: Skeleton
      rounds: True
      competition_type: SINGLE
      result_at: '0'
      article: das


- name: Eishockey
  topic_id: null
  result_type: POINTS
  result_digits: 1
  competition_term: Spiel
  article: das
  disciplines:
    - name: Gruppe A
      rounds: True
      competition_type: TOURNAMENT
      result_at: '0'
      article: das
    - name: Gruppe B
      rounds: True
      competition_type: TOURNAMENT
      result_at: '0'
      article: das
    - name: Gruppe C
      rounds: True
      competition_type: TOURNAMENT
      result_at: '0'
      article: das
    - name: Viertelfinale
      rounds: True
      competition_type: TOURNAMENT
      result_at: '0'
      article: das
    - name: Halbfinale
      rounds: True
      competition_type: TOURNAMENT
      result_at: '0'
      article: das
    - name: Finale
      rounds: True
      competition_type: TOURNAMENT
      result_at: '0'
      article: das
    - name: Qualifikationsrunde
      rounds: True
      competition_type: TOURNAMENT
      result_at: '0'
      article: das
    - name: 3. Platz
      rounds: True
      competition_type: TOURNAMENT
      result_at: '0'
      article: das
    - name: 7. Platz
      rounds: True
      competition_type: TOURNAMENT
      result_at: '0'
      article: das
    - name: 5. Platz
      rounds: True
      competition_type: TOURNAMENT
      result_at: '0'
      article: das
    - name: Platzierungsrunde
      rounds: True
      competition_type: TOURNAMENT
      result_at: '0'
      article: das


- name: Bob
  topic_id: null
  result_type: TIME
  result_digits: 2
  competition_term: Rennen
  article: das
  disciplines:
    - name: Zweierbob
      rounds: True
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: Viererbob
      competition_type: SINGLE
      result_at: '0'
      article: das

- name: Curling
  topic_id: null
  result_type: POINTS
  result_digits: 1
  competition_term: Spiel
  article: das
  disciplines:
    - name: Round Robin
      rounds: True
      competition_type: TOURNAMENT
      result_at: '0'
      article: das
    - name: Tie-breaker
      rounds: True
      competition_type: TOURNAMENT
      result_at: '0'
      article: das
    - name: Viertelfinale
      rounds: True
      competition_type: TOURNAMENT
      result_at: '0'
      article: das
    - name: Halbfinale
      rounds: True
      competition_type: TOURNAMENT
      result_at: '0'
      article: das
    - name: 3. Platz
      rounds: True
      competition_type: TOURNAMENT
      result_at: '0'
      article: das
    - name: Finale
      rounds: True
      competition_type: TOURNAMENT
      result_at: '0'
      article: das

- name: Eiskunstlauf
  topic_id: null
  result_type: POINTS
  result_digits: 1
  competition_term: Event
  article: das
  disciplines:
    - name: Einzel
      rounds: True
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: Teamwettbewerb
      rounds: True
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: Eistanz
      rounds: True
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: Paarlauf
      rounds: True
      competition_type: SINGLE
      result_at: '0'
      article: das

- name: Eisschnelllauf
  topic_id: null
  result_type: POINTS
  result_digits: 1
  competition_term: Rennen
  article: das
  disciplines:
    - name: Teamverfolgung
      rounds: True
      competition_type: TOURNAMENT
      result_at: '0'
      article: das
    - name: 10000 m
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: 1500 m
      rounds: True
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: Teamwettbewerb
      rounds: True
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: Teamwettbewerb
      rounds: True
      competition_type: SINGLE
      result_at: '0'
      article: das

- name: Nordische Kombination
  topic_id: 1827
  result_type: TIME
  result_digits: 1
  competition_term: Rennen
  article: das
  disciplines:
    - name: Normalschanze
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: Großschanze
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: Team
      competition_type: SINGLE
      result_at: '0'
      article: das

- name: Rodeln
  topic_id: null
  result_type: TIME
  result_digits: 3
  competition_term: Rennen
  article: das
  disciplines:
    - name: Einsitzer
      rounds: True
      competition_type: SINGLE
      result_at: '0'
      article: der
    - name: Doppelsitzer
      competition_type: SINGLE
      result_at: '0'
      article: der
    - name: Teamwettbewerb
      competition_type: SINGLE
      result_at: '0'
      article: der

- name: Shorttrack
  topic_id: null
  result_type: TIME
  result_digits: 1
  competition_term: Rennen
  article: das
  disciplines:
    - name: Staffel
      rounds: True
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: 1000 m
      rounds: True
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: 1500 m
      rounds: True
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: 500 m
      rounds: True
      competition_type: SINGLE
      result_at: '0'
      article: das

- name: Ski Langlauf
  topic_id: 1764
  result_type: Time
  result_digits: 1
  competition_term: Rennen
  article: das
  disciplines:
    - name: Sprint
      rounds: True
      competition_type: TOURNAMENT
      result_at: '0'
      article: das
    - name: Staffel
      competition_type: RACE
      result_at: '0'
      article: das
    - name: Skating
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: Skiathlon
      competition_type: RACE
      result_at: '0'
      article: das
    - name: Skating
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: 50km
      competition_type: RACE
      result_at: '0'
      article: das
    - name: 30km
      competition_type: RACE
      result_at: '0'
      article: das

- name: Snowboard
  topic_id: null
  result_type: POINTS
  result_digits: 1
  competition_term: Event
  article: das
  disciplines:
    - name: Halfpipe
      rounds: True
      competition_type: SINGLE
      result_at: '3'
      article: das
    - name: Slopestyle
      rounds: True
      competition_type: SINGLE
      result_at: '3'
      article: das
    - name: Snowboardcross
      rounds: True
      competition_type: TOURNAMENT
      result_at: '0'
      article: das
    - name: Big Air
      rounds: True
      competition_type: SINGLE
      result_at: '3'
      article: das
    - name: Parallel Riesenslalom
      rounds: True
      competition_type: TOURNAMENT
      result_at: '3'
      article: das

- name: Ski Freestyle
  topic_id: null
  result_type: POINTS
  result_digits: 1
  competition_term: Event
  article: das
  disciplines:
    - name: Aerials
      rounds: True
      competition_type: SINGLE
      result_at: '3'
      article: das
    - name: Buckelpiste
      rounds: True
      competition_type: SINGLE
      result_at: '0'
      article: die
    - name: Halfpipe
      rounds: True
      competition_type: SINGLE
      result_at: '3'
      article: die
    - name: Slopestyle
      rounds: True
      competition_type: SINGLE
      result_at: '3'
      article: die
    - name: Ski Cross
      rounds: True
      competition_type: TOURNAMENT
      result_at: '0'
      article: die
...