---
# result_type: TIME | POINTS
# competition_type: SINGLE | RACE | TOURNAMENT

- name: Biathlon
  picture_url: https://i.imgur.com/XpHMpTt.png
  topic_id: 1814
  result_type: TIME
  result_digits: 1
  competition_term: Rennen
  article: das
  slug: biathlon-sportler
  disciplines:
    - name: Einzel
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: Staffel
      competition_type: RACE
      result_at: '0'
      article: die
    - name: Massenstart
      competition_type: RACE
      result_at: '0'
      article: der
    - name: Verfolgung
      competition_type: RACE
      result_at: '0'
      article: die
    - name: Sprint
      competition_type: SINGLE
      result_at: '0'
      article: der

- name: Ski Alpin
  picture_url: https://i.imgur.com/RPpJAbn.png
  topic_id: 1773
  result_type: TIME
  result_digits: 2
  competition_term: Rennen
  article: das
  slug: ski-alpin-sportler
  disciplines:
    - name: Abfahrt
      competition_type: SINGLE
      result_at: '0'
      article: die
    - name: Super-G
      competition_type: SINGLE
      result_at: '0'
      article: der
    - name: Super G
      competition_type: SINGLE
      result_at: '0'
      article: der
    - name: Riesenslalom
      competition_type: SINGLE
      result_at: '0'
      article: der
    - name: Slalom
      competition_type: SINGLE
      result_at: '0'
      article: der
    - name: Kombination
      competition_type: SINGLE
      result_at: '0'
      article: die
    - name: Parallel
      competition_type: SINGLE
      result_at: '0'
      article:

- name: Skispringen
  picture_url: https://i.imgur.com/eTD5Uqh.png
  topic_id: 1789
  result_type: POINTS
  result_digits: 1
  competition_term: Springen
  article: das
  slug: skispringen-sportler
  disciplines:
    - name: Großschanze
      rounds: True
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: Normalschanze
      rounds: True
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: Flugschanze
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: Team Normalschanze
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: Teamspringen
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: Team Normalschanze
      competition_type: SINGLE
      result_at: '0'
      article: das

- name: Skeleton
  picture_url: https://i.imgur.com/AvqEBPj.png
  topic_id: null
  result_type: TIME
  result_digits: 2
  competition_term: Rennen
  article: das
  slug: skeleton-sportler
  disciplines:
    - name: Skeleton
      rounds: True
      competition_type: SINGLE
      result_at: '0'
      article: das


- name: Eishockey
  picture_url: https://i.imgur.com/VvMFXD0.png
  topic_id: null
  result_type: POINTS
  result_digits: 1
  competition_term: Spiel
  article: das
  slug: eishockey-sportler
  disciplines:
    - name: Gruppe A
      rounds: True
      competition_type: TOURNAMENT
      result_at: '0'
      article: das
    - name: Gruppe B
      rounds: True
      competition_type: TOURNAMENT
      result_at: '0'
      article: das
    - name: Gruppe C
      rounds: True
      competition_type: TOURNAMENT
      result_at: '0'
      article: das
    - name: Viertelfinale
      rounds: True
      competition_type: TOURNAMENT
      result_at: '0'
      article: das
    - name: Halbfinale
      rounds: True
      competition_type: TOURNAMENT
      result_at: '0'
      article: das
    - name: Finale
      rounds: True
      competition_type: TOURNAMENT
      result_at: '0'
      article: das
    - name: Qualifikationsrunde
      rounds: True
      competition_type: TOURNAMENT
      result_at: '0'
      article: das
    - name: 3. Platz
      rounds: True
      competition_type: TOURNAMENT
      result_at: '0'
      article: das
    - name: 7. Platz
      rounds: True
      competition_type: TOURNAMENT
      result_at: '0'
      article: das
    - name: 5. Platz
      rounds: True
      competition_type: TOURNAMENT
      result_at: '0'
      article: das
    - name: Platzierungsrunde
      rounds: True
      competition_type: TOURNAMENT
      result_at: '0'
      article: das


- name: Bob
  picture_url: https://i.imgur.com/35nk83n.png
  topic_id: null
  result_type: TIME
  result_digits: 2
  competition_term: Rennen
  article: das
  slug: bob-sportler
  disciplines:
    - name: Zweierbob
      rounds: True
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: Viererbob
      rounds: True
      competition_type: SINGLE
      result_at: '0'
      article: das

- name: Curling
  picture_url: https://i.imgur.com/8yL0Eg8.png
  topic_id: null
  result_type: POINTS
  result_digits: 1
  competition_term: Spiel
  article: das
  slug: regeln-curling
  disciplines:
    - name: Round Robin
      rounds: True
      competition_type: TOURNAMENT
      result_at: '0'
      article: das
    - name: Tie-breaker
      rounds: True
      competition_type: TOURNAMENT
      result_at: '0'
      article: das
    - name: Viertelfinale
      rounds: True
      competition_type: TOURNAMENT
      result_at: '0'
      article: das
    - name: Halbfinale
      rounds: True
      competition_type: TOURNAMENT
      result_at: '0'
      article: das
    - name: 3. Platz
      rounds: True
      competition_type: TOURNAMENT
      result_at: '0'
      article: das
    - name: Finale
      rounds: True
      competition_type: TOURNAMENT
      result_at: '0'
      article: das

- name: Eiskunstlauf
  picture_url: https://i.imgur.com/lXW3RYo.png
  topic_id: null
  result_type: POINTS
  result_digits: 1
  competition_term: Event
  article: das
  slug: eiskunstlauf-sportler
  disciplines:
    - name: Einzel
      rounds: True
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: Teamwettbewerb
      rounds: True
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: Eistanz
      rounds: True
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: Paarlauf
      rounds: True
      competition_type: SINGLE
      result_at: '0'
      article: das

- name: Eisschnelllauf
  picture_url: https://i.imgur.com/dGK1QZQ.png
  topic_id: null
  result_type: TIME
  result_digits: 2
  competition_term: Rennen
  article: das
  slug: eisschnelllauf-sportler
  disciplines:
    - name: Teamverfolgung
      rounds: True
      competition_type: TOURNAMENT
      result_at: '0'
      article: das
    - name: 10000 m
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: 1500 m
      rounds: True
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: Teamwettbewerb
      rounds: True
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: 5000 m
      rounds: True
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: 500 m
      rounds: True
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: 1000 m
      rounds: True
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: 3000 m
      rounds: True
      competition_type: SINGLE
      result_at: '0'
      article: das

- name: Nordische Kombination
  picture_url: https://i.imgur.com/AoKjzhg.png
  topic_id: 1827
  result_type: TIME
  result_digits: 1
  competition_term: Rennen
  article: das
  slug: nordische-kombination-sportler
  disciplines:
    - name: Normalschanze
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: Großschanze
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: Team
      competition_type: SINGLE
      result_at: '0'
      article: das

- name: Rodeln
  picture_url: https://i.imgur.com/nhG96lr.png
  topic_id: null
  result_type: TIME
  result_digits: 3
  competition_term: Rennen
  article: das
  slug: rodeln-sportler
  disciplines:
    - name: Einsitzer
      rounds: True
      competition_type: SINGLE
      result_at: '0'
      article: der
    - name: Doppelsitzer
      competition_type: SINGLE
      result_at: '0'
      article: der
    - name: Teamwettbewerb
      competition_type: SINGLE
      result_at: '0'
      article: der

- name: Shorttrack
  picture_url: https://i.imgur.com/AaR8lJw.png
  topic_id: null
  result_type: TIME
  result_digits: 1
  competition_term: Rennen
  article: das
  slug: shorttrack-sportler
  disciplines:
    - name: Staffel
      rounds: True
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: 1000 m
      rounds: True
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: 1500 m
      rounds: True
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: 500 m
      rounds: True
      competition_type: SINGLE
      result_at: '0'
      article: das

- name: Ski Langlauf
  picture_url: https://i.imgur.com/ewbiKsx.png
  topic_id: 1764
  result_type: Time
  result_digits: 1
  competition_term: Rennen
  article: das
  slug: skilanglauf-sportler
  disciplines:
    - name: Sprint
      rounds: True
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: Staffel
      competition_type: RACE
      result_at: '0'
      article: das
    - name: Skating
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: Skiathlon
      competition_type: RACE
      result_at: '0'
      article: das
    - name: Skating
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: 50km
      competition_type: RACE
      result_at: '0'
      article: das
    - name: 30km
      competition_type: RACE
      result_at: '0'
      article: das
    - name: Freistil
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: 10km
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: 15km
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: Verfolgung
      competition_type: RACE
      result_at: '0'
      article: das


- name: Snowboard
  picture_url: https://i.imgur.com/1TaYOn1.png
  topic_id: null
  result_type: POINTS
  result_digits: 1
  competition_term: Event
  article: das
  slug: snowboard-sportler
  disciplines:
    - name: Halfpipe
      rounds: True
      competition_type: SINGLE
      result_at: '3'
      article: das
    - name: Slopestyle
      rounds: True
      competition_type: SINGLE
      result_at: '3'
      article: das
    - name: Snowboardcross
      rounds: True
      competition_type: SINGLE
      result_at: '0'
      article: das
    - name: Big Air
      rounds: True
      competition_type: SINGLE
      result_at: '3'
      article: das
    - name: Parallel
      rounds: True
      competition_type: TOURNAMENT
      result_at: '3'
      article: das

- name: Ski Freestyle
  picture_url: https://i.imgur.com/wSURv4K.png
  topic_id: null
  result_type: POINTS
  result_digits: 1
  competition_term: Event
  article: das
  slug: freestyle-sportler
  disciplines:
    - name: Aerials
      rounds: True
      competition_type: SINGLE
      result_at: '3'
      article: das
    - name: Buckelpiste
      rounds: True
      competition_type: SINGLE
      result_at: '3'
      article: die
    - name: Halfpipe
      rounds: True
      competition_type: SINGLE
      result_at: '3'
      article: die
    - name: Slopestyle
      rounds: True
      competition_type: SINGLE
      result_at: '3'
      article: die
    - name: Ski Cross
      rounds: True
      competition_type: SINGLE
      result_at: '0'
      article: die
...
