---

- include_tasks: utils/k8s-creds.yml
- name: Store Kubernetes Secret
  kubernetes:
    api_endpoint: "api.{{ k8s_url }}"
    username: admin
    password: "{{ k8s_credentials }}"
    inline_data: |
      {% include 'utils/k8s-secret.yml.j2' %}
