---

- block:
    - name: Gather Kubernetes Credentials
      command: "kops get secrets kube --type secret -oplaintext"
      register: k8s_credentials_fetch
      changed_when: false
      check_mode: no
    - name: Cache Kubernetes Credentials
      set_fact:
        k8s_credentials: "{{ k8s_credentials_fetch.stdout }}"
  when: k8s_credentials is not defined
