# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200, verbose_name='Überschrift')),
                ('text', models.CharField(max_length=200, verbose_name='Intro-Text')),
                ('media', models.FileField(blank=True, null=True, upload_to='', verbose_name='Medien-Anhang Intro')),
                ('media_note', models.CharField(blank=True, help_text='z. B. Bildrechte', max_length=128, null=True, verbose_name='Anmerkung')),
                ('attachment_id', models.CharField(blank=True, help_text='Wird automatisch ausgefüllt', max_length=64, null=True, verbose_name='Facebook Attachment ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Erstellt')),
                ('published', models.BooleanField(default=False, verbose_name='Freigegeben')),
                ('delivered', models.BooleanField(default=False, help_text='Wurde diese Meldung bereits in einem Highlights-Push vom Bot versendet?', verbose_name='Versendet')),
            ],
            options={
                'verbose_name_plural': 'Meldungen',
                'verbose_name': 'Meldung',
            },
        ),
        migrations.CreateModel(
            name='ReportFragment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=20, verbose_name='Frage')),
                ('text', models.CharField(max_length=600, verbose_name='Text')),
                ('media', models.FileField(blank=True, null=True, upload_to='', verbose_name='Medien-Anhang')),
                ('media_note', models.CharField(blank=True, help_text='z. B. Bildrechte', max_length=128, null=True, verbose_name='Anmerkung')),
                ('attachment_id', models.CharField(blank=True, help_text='Wird automatisch ausgefüllt', max_length=64, null=True, verbose_name='Facebook Attachment ID')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragments', related_query_name='fragment', to='backend.Report')),
            ],
            options={
                'verbose_name_plural': 'Meldungs-Fragmente',
                'verbose_name': 'Meldungs-Fragment',
            },
        ),
        migrations.RemoveField(
            model_name='pushfragment',
            name='push',
        ),
        migrations.DeleteModel(
            name='Push',
        ),
        migrations.DeleteModel(
            name='PushFragment',
        ),
    ]
