# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20171108_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='push',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', related_query_name='report', to='backend.Push'),
        ),
    ]
