# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_storyfragment_link_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='push',
            name='published',
            field=models.BooleanField(default=False, help_text='Solange dieser Haken nicht gesetzt ist, wird dieser Push nicht versendet, auch wenn der konfigurierte Zeitpunkt erreicht wird.', verbose_name='Freigegeben'),
        ),
        migrations.AlterField(
            model_name='report',
            name='delivered',
            field=models.BooleanField(default=False, verbose_name='Versendet'),
        ),
        migrations.AlterField(
            model_name='report',
            name='published',
            field=models.BooleanField(default=False, help_text='Solange dieser Haken nicht gesetzt ist, wird diese Meldung nicht versendet, weder in terminierten Highlight-Pushes noch an Abonnenten von bestimmten Sportarten, Sportlern, Disziplinen etc.', verbose_name='Freigegeben'),
        ),
    ]
